### ISSUE TITLE
i had a problem but fixed it ?

### ISSUE THREAD

**Issue by darknightmc80** [AsjadOooO/Zero-attacker#55]
i had a problem when i ran it it said python not found when i chose opction 1 

Fix: (idk but worked for me) edit the files so when it runs python on windows to py and when run on linux to python3

**Comment by darknightmc80** [comment]
sorry for the bad spelling my main is not english

**Comment by darknightmc80** [comment]
Click here to visit my GitHub profile: https://github.com/TejasLamba2006
Traceback (most recent call last):
  File "/home/darknightmc80/Zero-attacker/Zero-Tool/nuke-bot/main.py", line 18, in <module>
    process = subprocess.Popen(command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, shell=False)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.11/subprocess.py", line 1950, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: 'node'
