### ISSUE TITLE
broken code

### ISSUE THREAD

**Issue by KilluaZo1dyck** [AsjadOooO/Zero-attacker#8]
Traceback (most recent call last):
  File "<Discord-Token-BruteForce.py>", line 3, in <module>
  File "<frozen Discord-Token-BruteForce>", line 19, in <module>
TypeError: encode() argument 'encoding' must be str, not builtin_function_or_method

**Comment by AsjadOooO** [comment]
Fixed

**Comment by AsjadOooO** [comment]
ended
